### ISSUE TITLE
Ingress doesn't conform to v1 spec

### ISSUE THREAD

**Issue by pixil98** [ressu/kube-plex#23]
It looks like the ingress was updated to use the v1 spec, but it isn't compatible with the new spec.

**Comment by ressu** [comment]
Thanks for the report, could you provide the error you are seeing with the ingress. Since I'm not using the ingress definition myself (or the helm chart in general) it's a bit hard to catch all issues.

I think the issue could be missing pathType in the paths definition, but I just want to confirm that there aren't more issues there.

**Comment by pixil98** [comment]
There are two problems I've found so far, the first is that the backend.service needs to be updated to:

```
service: 
  name: {{ $serviceName }}
  port: 
    name: pms
```

The second issue is the missing pathType.

**Comment by pixil98** [comment]
I've applied both changes and I'm getting futher, now I'm running into this error: 

```
Deployment is not ready: plex/plex-kube-plex. 0 out of 1 expected pods are ready
  Normal  error  7m7s                 helm-controller  reconciliation failed: Helm install failed: timed out waiting for the condition
  Normal  error  7m7s                 helm-controller  reconciliation failed: Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "plex": the object has been modified; please apply your changes to the latest version and try again
  Normal  error  98s (x15 over 7m7s)  helm-controller  reconciliation failed: install retries exhausted
```

I'm pretty new to helm, I'm guessing there is some checksum or versioning other than the chart version (which I incremented to 0.3.1) that don't match up with the changes.

**Comment by brandon099** [comment]
> I've applied both changes and I'm getting further, now I'm running into this error:
> 
> ```
> Deployment is not ready: plex/plex-kube-plex. 0 out of 1 expected pods are ready
>   Normal  error  7m7s                 helm-controller  reconciliation failed: Helm install failed: timed out waiting for the condition
>   Normal  error  7m7s                 helm-controller  reconciliation failed: Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "plex": the object has been modified; please apply your changes to the latest version and try again
>   Normal  error  98s (x15 over 7m7s)  helm-controller  reconciliation failed: install retries exhausted
> ```
> 
> I'm pretty new to helm, I'm guessing there is some checksum or versioning other than the chart version (which I incremented to 0.3.1) that don't match up with the changes.

That is the helm-controller in Flux that timed out waiting for the `helm` install to complete. Are there any logs that indicate what Helm was/is waiting for? Are there resources actually running, and helm just timed out before it could finish?

**Comment by pixil98** [comment]
You're right, it was a problem with the nfs mounts. I fixed those and everything is deploying. I'll submit a pull request with the updated yaml.

**Comment by pixil98** [comment]
Looks like you beat me to it. Thanks for the help.

**Comment by brandon099** [comment]
Okay perfect. I have already created #24 with the updated ingress spec, and linked it here already.
