### ISSUE TITLE
Allow custom probes for main Plex pod

### ISSUE THREAD

**Issue by brandon099** [ressu/kube-plex#3]
The current hard-coded values for the readiness and liveness probes seem a bit fragile. It would be nice to be able to set values here (for example: changing from httpGet to tcpSocket and adjust polling intervals). I'll submit a PR, but wanted to see if there was any preference as to how it was implemented before working on this.

**Comment by ressu** [comment]
Marking this as closed since I forgot to mark it fixed with the PR. Thanks again.
