### ISSUE TITLE
[Feature Request] Allow nodeSelector reflection for spawned jobs/pods

### ISSUE THREAD

**Issue by rkbennett** [ressu/kube-plex#45]
When a transcode job/pod is created, it currently doesn't appear to reflect any custom nodeSelectors into the created resource. This would be handy if, for instance, you have some nodes in your k8s cluster which are better suited to handle the transcoding. In theory you should be able to pull the pods nodeSelectors in a similar way to how you pull the kube-plex annotations during resource creation.

**Comment by ressu** [comment]
Marking this as fixed too.
