### ISSUE TITLE
Default value (and instructions) for image use munnerz and not ressu

### ISSUE THREAD

**Issue by ohthehugemanatee** [ressu/kube-plex#8]
Munnerz is so out of date now, there are incompatibilities with current k8s API. The one I ran into is that it expects the pod's namespace in `$KUBE_NAMESPACE`. When I override the value for the image to `ghcr.io/ressu/kube-plex` this issue is resolved.

This should be updated in the `values.yaml` for this repo.

**Comment by ressu** [comment]
Back when I was working on my branch, I didn't want to overwrite the image locations, but considering that the fork is now taking a life of its own, it makes sense to change the images.
