### ISSUE TITLE
Not using latest official plex image, instead hard-coded: plexinc/pms-docker:1.16.0.1226-7eb2c8f6f

### ISSUE THREAD

**Issue by karezza** [ressu/kube-plex#9]
Is there a reason to keep using plexinc/pms-docker:1.16.0.1226-7eb2c8f6f rather than the latest?

**Comment by ressu** [comment]
Go for latest, I'll update the values later this week to match what I have in my homelab. I'm reluctant to use `:latest` since it's a bad practice in general, but I think it might make things easier to set up initially regardless of my reservations 😆
